application: Modeify
name: Modeify
domain: modeify.co

announcements:

organization:
  name: Conveyal
  url: http://conveyal.com

# Support Email Address
email:
  name: Trevor Gerhardt
  address: tgerhardt@conveyal.com

# Geocoding
geocode:
  center: -77.105933,38.880148
  start_address: 4301 13th St NW Washington, DC 20011
  end_address: 2100 Wilson Blvd, Arlington, VA

# Default application values
api_url: /api
base_url: http://localhost:5000

google_site_verification:

mapbox_access_token:
mapbox_map_id:

otp:
  host: localhost
  path: /otp/routers/default
  port: 8080
s3_bucket: ''
segmentio_key: ''
static_url: /assets

# Custom Environments
environments:

  # For running tests
  test:

  # Default & development
  development:

  # Staging / QA / Production
  production:
    base_url:
    opsworks:
      otp_app_id:
      otp_layer_id:
      stack_id:
    s3_bucket:
    segmentio_key:
    static_url:
